catalogue/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('product_catalog.urls'))
]
print('asd')

product_catalog/urls.py
# -*- coding: utf-8 -*-
""" Product Catalog: Defaults urls """

from django.conf.urls import url
from django.views.generic import TemplateView

from product_catalog.views.category import CategoryListView, CategoryDetailView
from product_catalog.views.product import ProductListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView
from product_catalog.settings import FRONT_MANAGEMENT

app_name = 'product_catalog'

urlpatterns = []
if FRONT_MANAGEMENT:
    urlpatterns += [
        url(r'^products/add/$', ProductCreateView.as_view(), name='product_add'),
        url(r'^products/update/(?P<pk>[0-9]+)/$', ProductUpdateView.as_view(), name='product_update'),
        url(r'^products/delete/(?P<pk>[0-9]+)/$', ProductDeleteView.as_view(), name='product_delete'),
    ]

urlpatterns += [
    # Category
    url(r'^categories/$', CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<slug>[-\w]+)/$', CategoryDetailView.as_view(), name='category_detail'),

    # Product
    url(r'^products/$', ProductListView.as_view(), name='product_list'),
    url(r'^products/(?P<slug>[-\w]+)/$', ProductDetailView.as_view(), name='product_detail'),

    # Home
    url(r'^$', TemplateView.as_view(template_name='product_catalog/home.html'), name='product_home'),
]

product_catalog/models/category.py
# -*- coding: utf-8 -*-
""" Category model for Product Catalog """

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from mptt.managers import TreeManager
from mptt.models import MPTTModel
from mptt.models import TreeForeignKey

from product_catalog.managers import ProductsRelatedPublishedManager
from product_catalog.managers import product_published


@python_2_unicode_compatible
class Category(MPTTModel):
    """
    Simple model for categorizing products.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255, db_index=True,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('parent category'))

    objects = TreeManager()
    published = ProductsRelatedPublishedManager()

    @models.permalink
    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return 'product_catalog:category_detail', (self.slug,)

    def __str__(self):
        return self.title

    def product_published(self):
        """
        Returns category's published products.
        """
        return product_published(self.products)

    class Meta:
        """
        Category's meta information.
        """
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta information.
        """
        order_insertion_by = ['title']

product_catalog/models/product.py
# -*- coding: utf-8 -*-
""" Product Catalog: Product model """

from product_catalog.models.product_abstract import AbstractProduct


class Product(AbstractProduct):
    pass

product_catalog/models/product_abstract.py
# -*- coding: utf-8 -*-
""" Product Catalog: Product models"""

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.contrib.postgres.fields import JSONField
from product_catalog.settings import UPLOAD_TO
from product_catalog.managers import DRAFT, HIDDEN, PUBLISHED
from product_catalog.managers import ProductPublishedManager
from product_catalog.models.category import Category

from django_extensions.db.fields import AutoSlugField


@python_2_unicode_compatible
class BaseProduct(models.Model):
    """
    Abstract base product model class providing the base fields and methods
    """
    title = models.CharField(_('title'), max_length=255, null=True)
    slug = AutoSlugField(_('slug'), max_length=255, populate_from=['title', 'id'], unique=True, db_index=True,
                         overwrite=True)
    creation_date = models.DateTimeField(_('creation date'), default=timezone.now)
    last_update = models.DateTimeField(_('last update'), auto_now=True)
    categories = models.ManyToManyField(Category,
                                        blank=True,
                                        related_name='products',
                                        verbose_name=_('categories'))
    objects = models.Manager()

    @models.permalink
    def get_absolute_url(self):
        """ """
        return 'product_catalog:product_detail', (self.slug,)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        """
        BaseProduct's meta informations.
        """
        abstract = True
        ordering = ['-creation_date']
        get_latest_by = 'creation_date'
        verbose_name = _('product')
        verbose_name_plural = _('products')


class PublicationProduct(models.Model):
    """
    Abstract model class providing the publication fields and methods
    """

    STATUS_CHOICES = ((DRAFT, _('draft')),
                      (HIDDEN, _('hidden')),
                      (PUBLISHED, _('published')))

    status = models.IntegerField(_('status'), db_index=True, choices=STATUS_CHOICES, default=PUBLISHED)
    start_publication = models.DateTimeField(_('start publication'), blank=True, null=True,
                                             help_text=_('Start date of publication.'))
    end_publication = models.DateTimeField(_('end publication'), blank=True, null=True,
                                           help_text=_('End date of publication.'))

    published = ProductPublishedManager()

    class Meta:
        abstract = True

    @property
    def is_actual(self):
        """
        Checks if a product is in its publication period.
        """
        now = timezone.now()
        if self.start_publication and now < self.start_publication:
            return False

        if self.end_publication and now >= self.end_publication:
            return False
        return True

    @property
    def is_visible(self):
        """
        Checks if a product is visible and published.
        """
        return self.is_actual and self.status == PUBLISHED

    @property
    def previous_entry(self):
        """
        Returns the previous published entry if exists.
        """
        return self.previous_next_entries[0]

    @property
    def next_entry(self):
        """
        Returns the next published entry if exists.
        """
        return self.previous_next_entries[1]

    @property
    def previous_next_entries(self):
        """
        Returns and caches a tuple containing the next
        and previous published entries.
        Only available if the entry instance is published.
        """
        previous_next = getattr(self, 'previous_next', None)

        if previous_next is None:
            if not self.is_visible:
                previous_next = (None, None)
                setattr(self, 'previous_next', previous_next)
                return previous_next

            entries = list(self.__class__.published.all())
            index = entries.index(self)
            try:
                previous = entries[index + 1]
            except IndexError:
                previous = None

            if index:
                _next = entries[index - 1]
            else:
                _next = None
            previous_next = (previous, _next)
            setattr(self, 'previous_next', previous_next)
        return previous_next


class OwnerProduct(models.Model):
    """ Abstract class to add an owner to the the product """
    owner = models.ForeignKey(User, blank=True, null=True, related_name='products', verbose_name=_('owner'))

    class Meta:
        abstract = True


class TaggedProduct(models.Model):
    tags = TaggableManager()

    class Meta:
        abstract = True


class DynamicModel(models.Model):
    dynamic_field = JSONField()


class AbstractProduct(
    BaseProduct,
    PublicationProduct,
    OwnerProduct,
    #TaggedProduct,
    DynamicModel
):
    """
    Final abstract product model class assembling
    all the abstract product model classes into a single one.
    In this manner we can override some fields without
    reimplementing all the AbstractProduct.
    """

    class Meta(BaseProduct.Meta):
        abstract = True

product_catalog/admin/forms.py
# -*- coding: utf-8 -*-
""" Product Catalog: admin forms """

from django import forms
from mptt.forms import TreeNodeMultipleChoiceField
from product_catalog.models.category import Category


class CategoryAdminForm(forms.ModelForm):
    """
    Form for Category's Admin.
    Displays the level of hierarchy between parent / children
    """
    categories = TreeNodeMultipleChoiceField(
        level_indicator='---',
        required=False,
        queryset=Category.objects.all())

product_catalog/forms.py
# -*- coding: utf-8 -*-
""" Product Catalog: forms """

from django import forms
from mptt.forms import TreeNodeMultipleChoiceField
from product_catalog.models.category import Category
from product_catalog.models.product import Product

from product_catalog.settings import FORM_UPDATE_FIELDS, FORM_CREATE_FIELDS


class CategoryForm(forms.ModelForm):
    """
    Form for Category's
    Displays the level of hierarchy between parent / children
    """
    categories = TreeNodeMultipleChoiceField(
        level_indicator='---',
        required=False,
        queryset=Category.objects.all())


class CategoryUpdateForm(CategoryForm):
    class Meta:
        model = Product
        fields = FORM_UPDATE_FIELDS


class CategoryCreateForm(CategoryForm):
    class Meta:
        model = Product
        fields = FORM_CREATE_FIELDS

product_catalog/views/category.py
# -*- coding: utf-8 -*-
""" Product Catalog: Category view """

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404

from product_catalog.models.category import Category
from product_catalog.models.product import Product
from product_catalog.settings import PAGINATION


class CategoryListView(ListView):
    """ """
    model = Category
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        return context

class CategoryDetailView(ListView):
    """ """
    template_name = 'product_catalog/category_detail.html'
    context_object_name = "product_list"
    paginate_by = PAGINATION

    def get_queryset(self, **kwargs):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Product.published.filter(categories=self.category)

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

product_catalog/views/product.py
# -*- coding: utf-8 -*-
""" Product Catalog: Product view """

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from product_catalog.models.product import Product
from product_catalog.settings import PAGINATION
from product_catalog.views.mixins.auth_mixins import FrontManagementIsOpenMixin, AccessMixin, CreateAccessMixin

from product_catalog.forms import CategoryUpdateForm, CategoryCreateForm

class ProductListView(ListView):
    """ """
    context_object_name = "product_list"
    paginate_by = PAGINATION

    def get_queryset(self, **kwargs):
        return Product.published.all()


class ProductDetailView(DetailView):
    """ """
    context_object_name = "product"

    def get_queryset(self, **kwargs):
        return Product.published.all()


class ProductCreateView(FrontManagementIsOpenMixin, CreateAccessMixin, CreateView):
    """ """
    model = Product
    form_class = CategoryCreateForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(FrontManagementIsOpenMixin, AccessMixin, UpdateView):
    """ """
    model = Product
    form_class = CategoryUpdateForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProductUpdateView, self).form_valid(form)


class ProductDeleteView(FrontManagementIsOpenMixin, AccessMixin, DeleteView):
    """ """
    model = Product
    success_url = reverse_lazy('product_catalog:product_list')

product_catalog/templates/product_catalog/_paginator.html
{% load i18n %}

{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
        {% endif %}
    </span>
</div>
{% endif %}

product_catalog/templates/product_catalog/base.html
{% extends "layout.html" %}
{% load i18n product_catalog %}

{% block content %}
    <h1>{% trans "Catalog" %}</h1>

    <h2>{% trans "Menu" %}</h2>
    <nav>
        <ul>
            <li><a href="{% url "product_catalog:product_home" %}">{% trans "home" %}</a></li>
            <li><a href="{% url "product_catalog:product_list" %}">{% trans "products" %}</a></li>
            <li><a href="{% url "product_catalog:category_list" %}">{% trans "categories" %}</a></li>
        </ul>

        {% if FRONT_MANAGEMENT %}
        <ul>
            <li><a href="{% url 'product_catalog:product_add' %}">{%  trans "Create new product" %}</a></li>
        </ul>
        {% endif %}
    </nav>

    <h2>{% trans "Categories" %}</h2>
    {% get_categories %}

    {% block catalog_content %}{% endblock %}
{% endblock %}

product_catalog/templates/product_catalog/category_detail.html
{% extends "product_catalog/base.html" %}
{% load i18n %}

{% block catalog_content %}
    <h2>{% trans "Category"  %}: {{ category.title }}</h2>

    <p>{{ category.content }}</p>

    {% trans "Products in this category" %}:
    <ul>
    {% for product in product_list %}
        <li><a href="{{ product.get_absolute_url }}">{{ product }}</a></li>
    {% empty %}
        <li>{% trans "Sorry, no products in this list." %}</li>
    {% endfor %}
    </ul>

    {% include "product_catalog/_paginator.html" %}
{% endblock %}

product_catalog/templates/product_catalog/category_list.html
{% extends "product_catalog/base.html" %}
{% load i18n mptt_tags %}

{% block catalog_content %}
    <h2>{% trans "Category List" %}</h2>

    <ul class="root">
        <li><a href="{% url "product_catalog:category_list" %}">{% trans "All categories" %}</a></li>
        {% recursetree category_list %}
        <li>
            <a href='{{ node.get_absolute_url }}'>{{ node }}</a>
            ({{ node.product_published.count }})
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
        {% endrecursetree %}
    </ul>


{% endblock %}

product_catalog/templates/product_catalog/home.html
{% extends "product_catalog/base.html" %}
{% load i18n product_catalog %}

{% block catalog_content %}
    <h2>{% trans "Home" %}</h2>

    <h3>{% trans "Last published products" %}</h3>
    {% get_last_products %}
{% endblock %}

product_catalog/templates/product_catalog/product_confirm_delete.html
{% extends "product_catalog/base.html" %}

{% load i18n %}

{% block catalog_content %}
    <h2>{%  trans "Delete Product" %}</h2>

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{%  trans 'Confirm' %}" />
    </form>
{% endblock %}

product_catalog/templates/product_catalog/product_detail.html
{% extends "product_catalog/base.html" %}
{% load i18n %}

{% block catalog_content %}
    <h2>{%  trans "Product" %}: {{ product.title }}</h2>

    {% if FRONT_MANAGEMENT %}
    <a href="{% url 'product_catalog:product_update' product.id %}">{% trans 'Update product' %}</a>
    <a href="{% url 'product_catalog:product_delete' product.id %}">{% trans 'Delete product' %}</a>
    {% endif %}

    {% if product.image %}
    <p><img src="{{ product.image.url }}" alt="{{ product.image_caption }}" /></p>
    {% endif %}
    <p>{{ product.content }}</p>

    {%  trans "Categories" %}:
    {% for category in product.categories.all %}
        <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    {%  trans "Tags" %}:
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object product as "tags" %}


    <ul>

    {% if product.previous_entry %}
        <li><a href="{% url 'product_catalog:product_detail' product.previous_entry.slug %}">prev</a></li>
    {% endif %}

    <li><a href="{% url 'product_catalog:product_list' %}">{% trans "back to the product list" %}</a></li>


    {% if product.next_entry %}
        <li><a href="{% url 'product_catalog:product_detail' product.next_entry.slug %}">next</a></li>
    {% endif %}
    </ul>

{% endblock %}

product_catalog/templates/product_catalog/product_form.html
{% extends "product_catalog/base.html" %}

{% load i18n %}

{% block catalog_content %}
    <h2>{%  trans "Create new product" %}</h2>

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{%  trans 'Save' %}" />
    </form>
{% endblock %}

product_catalog/templates/product_catalog/product_list.html
{% extends "product_catalog/base.html" %}
{% load i18n %}

{% block catalog_content %}
    <h2>{%  trans "Product List" %}</h2>



    <ul>
    {% for product in product_list %}
        <li>
            <a href='{{ product.get_absolute_url }}'>{{ product }}</a>
            {% if product.excerpt %}
                <br />{{ product.excerpt }}
            {% endif %}

            {% if product.categories.all %}
                <br />
                {%  trans "Categories" %}:
                {% for category in product.categories.all %}
                    <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            {% endif %}
        </li>
    {% empty %}
        <li>{%  trans "No products yet." %}</li>
    {% endfor %}
    </ul>

    {% include "product_catalog/_paginator.html" %}
{% endblock %}

product_catalog/templates/product_catalog/product_update_form.html
{% extends "product_catalog/base.html" %}

{% load i18n %}

{% block catalog_content %}
    <h2>{%  trans "Update Product" %}</h2>

    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{%  trans 'Update' %}" />
    </form>
{% endblock %}